#!/usr/bin/env node
/**
 * Generates the documentation that can be derived from IntuneTemplate/:
 *
 *   OVERZICHT.md                          the summary to share
 *   IntuneTemplate/README.md              the matrix and the folder layout
 *   IntuneTemplate/<PLAT>/README.md       every policy with what it does and where it lands
 *   IntuneTemplate/<PLAT>/<CAT>/*.md      per policy *every* setting it sets, and the standards it fulfils
 *
 * Every document in three languages: `X.md` in Dutch, `X.en.md` and `X.fr.md` next to it. Fixed
 * text is below as { nl, en, fr }; text from the data (`doel`, `note`, `faseWaarom`) comes from
 * IntuneTemplate/_i18n/<lang>.json — see lib/i18n.js.
 *
 * COMPLIANCE.md — the justification against ISO 27001, NIS2, CIS and NIST CSF — comes from
 * generate-compliance.js; here each policy only carries the reference to it.
 *
 * Each policy README also lists the Conditional Access policies that rely on it, from
 * docs/policies.json in the CA-Policies repo. With that repo next to this one the links come from
 * there and IntuneTemplate/_ca.json is rewritten as a copy; without it (in CI) they come from
 * that copy, so the output does not depend on what is cloned next to the repo.
 *
 * Generated and not written by hand: keeping nearly
 * a hundred policies with thousands of settings up to date goes wrong, and a table that is no
 * longer correct is worse than no table — because it still reads as if it were correct.
 *
 * Usage: node scripts/generate-docs.js [--check] [--missend]
 *   --check    writes nothing and exits 1 if a README is out of date (for CI).
 *   --missend  writes nothing and prints the texts without a translation as JSON.
 */

const fs = require("fs");
const path = require("path");
const { PLATFORMS, TYPE_TO_CATEGORY, readTemplates, parseBaseName, flattenSettings, packagePlan } = require("./lib/templates");
const { LANGS, variantPath, languageBar, Translator, reportMissing } = require("./lib/i18n");

const REPO_ROOT = path.resolve(__dirname, "..");
const TEMPLATE_DIR = path.join(REPO_ROOT, "IntuneTemplate");
const ASSIGNMENTS_PATH = path.join(TEMPLATE_DIR, "_assignments.json");
const MANIFEST_PATH = path.join(TEMPLATE_DIR, "_manifest.json");
const CONTROLS_PATH = path.join(TEMPLATE_DIR, "_controls.json");

/**
 * Welke CA-policies op een Intune-policy leunen, staat in de CA-Policies-repo
 * (docs/policies.json). Staat die repo ernaast, dan komt het daarvandaan en wordt de kopie in
 * _ca.json bijgewerkt; zo niet — in CI — dan uit die kopie. Zonder kopie zou de sectie in CI
 * wegvallen en het document bij elke run tussen twee versies wisselen.
 */
const CA_SNAPSHOT_PATH = path.join(TEMPLATE_DIR, "_ca.json");
const CA_SIBLINGS = ["CA-Policies", "CA-policies", "CIPP-Templates-ConditionalAccess"].map((d) => path.resolve(REPO_ROOT, "..", d));
/** Links naar de CA-kant gaan naar de gedeelde mirror: een relatief pad naar ../CA-Policies werkt op GitHub niet. */
const CA_URL = "https://github.com/ConXioN-ITCE/CIPP-Templates-ConditionalAccess/blob/main/";

const TYPE_LABEL = {
  Catalog: "Settings Catalog",
  Admin: "ADMX",
  Device: "Device config",
  deviceCompliancePolicies: "Compliance",
  AppProtection: "App Protection",
};

/**
 * De taal van het document dat nu gebouwd wordt. Module-breed in plaats van door elke functie
 * heen gegeven: settingRows() en shortValue() zitten vier aanroepen diep en hebben er alleen
 * een paar woorden van nodig.
 */
let V = new Translator("nl");

const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`;
const policies = (n) => plural(n, "policy", V.t({ nl: "policies", en: "policies", fr: "policies" }));

const generatedHeader = () =>
  V.t({
    nl: "<!-- Gegenereerd door scripts/generate-docs.js — niet met de hand bijwerken. -->",
    en: "<!-- Generated by scripts/generate-docs.js — do not edit by hand. -->",
    fr: "<!-- Généré par scripts/generate-docs.js — ne pas modifier à la main. -->",
  });

/** Kop van elk document: de generatiemelding en de taalbalk. */
const head = (fileName) => [generatedHeader(), "", languageBar(fileName, V.lang), ""];

/** Ankers in de handgeschreven documenten, per taal — die koppen zijn vertaald en dus hun ankers ook. */
const ANCHOR = {
  restore: { nl: "terugzetten-in-een-tenant", en: "restoring-into-a-tenant", fr: "restaurer-dans-un-tenant" },
};

function assignmentLabel(assignments, displayName) {
  const list = assignments[displayName];
  if (!list || list.length === 0) return "—";
  return list
    .map((a) => {
      const type = a.target["@odata.type"] || "";
      if (type.includes("allDevices")) return "All Devices";
      if (type.includes("allLicensedUsers")) return "All Users";
      if (type.includes("exclusionGroup")) return V.t({ nl: "groep (uitsluiting)", en: "group (exclusion)", fr: "groupe (exclusion)" });
      if (type.includes("group")) return V.t({ nl: "groep", en: "group", fr: "groupe" });
      return type.replace("#microsoft.graph.", "");
    })
    .join(", ");
}

/** Het aantal instellingen dat een policy werkelijk zet — de uitgeklapte telling. */
function settingCount(template) {
  if (template.type === "Catalog") return flattenSettings(template.raw.settings).settings.length;
  if (template.type === "Admin") return (template.raw.added || []).length;
  return "—";
}

function escapePipes(text) {
  return String(text).replace(/\|/g, "\\|");
}

/**
 * Waarde leesbaar maken. Bij een keuze-instelling is de waarde de settingDefinitionId met een
 * suffix eraan geplakt (`..._requiresecuritydevice_true`); dat voorvoegsel herhalen maakt de
 * tabel onleesbaar, dus alleen het suffix blijft over.
 */
function shortValue(id, value) {
  if (value === null || value === undefined) return "—";
  let text = String(value);
  if (id && text.startsWith(id + "_")) text = text.slice(id.length + 1);
  if (text === "") return V.t({ nl: "*(leeg)*", en: "*(empty)*", fr: "*(vide)*" });
  if (text.length > 110) text = text.slice(0, 107) + "…";
  return text;
}

/**
 * Klapt een settingInstance-boom uit met behoud van de nesting, want die nesting is
 * betekenisvol: een kind is alleen actief als zijn parent op de juiste waarde staat.
 * flattenSettings() gooit dat weg — prima voor een vergelijking, niet voor documentatie.
 */
function settingRows(instance, depth, rows) {
  if (!instance || typeof instance !== "object") return;
  const odataType = instance["@odata.type"] || "";
  const id = instance.settingDefinitionId;

  if (odataType.endsWith("ChoiceSettingInstance")) {
    const value = instance.choiceSettingValue || {};
    rows.push({ depth, id, value: shortValue(id, value.value) });
    for (const child of value.children || []) settingRows(child, depth + 1, rows);
  } else if (odataType.endsWith("ChoiceSettingCollectionInstance")) {
    const values = instance.choiceSettingCollectionValue || [];
    rows.push({ depth, id, value: values.map((v) => shortValue(id, v.value)).join(", ") });
    for (const v of values) for (const child of v.children || []) settingRows(child, depth + 1, rows);
  } else if (odataType.endsWith("SimpleSettingInstance")) {
    const value = instance.simpleSettingValue || {};
    const secret = (value["@odata.type"] || "").includes("Secret");
    const secretText = V.t({
      nl: "*(geheim — alleen geldig in de brontenant)*",
      en: "*(secret — only valid in the source tenant)*",
      fr: "*(secret — valable uniquement dans le tenant source)*",
    });
    rows.push({ depth, id, value: secret ? secretText : shortValue(null, value.value) });
  } else if (odataType.endsWith("SimpleSettingCollectionInstance")) {
    const values = (instance.simpleSettingCollectionValue || []).map((v) => String(v.value));
    rows.push({ depth, id, value: values.join(", ") });
  } else if (odataType.endsWith("GroupSettingCollectionInstance")) {
    const groups = instance.groupSettingCollectionValue || [];
    rows.push({ depth, id, value: groups.length > 1 ? `*(${groups.length} items)*` : V.t({ nl: "*(groep)*", en: "*(group)*", fr: "*(groupe)*" }) });
    groups.forEach((group, i) => {
      if (groups.length > 1) rows.push({ depth: depth + 1, id: null, value: null, separator: `item ${i + 1}` });
      for (const child of group.children || []) settingRows(child, depth + 1, rows);
    });
  } else {
    rows.push({ depth, id, value: V.t({ nl: `*(onbekend type ${odataType})*`, en: `*(unknown type ${odataType})*`, fr: `*(type inconnu ${odataType})*` }) });
  }
}

/** Eigenschappen van een compliance-, device- of app protection-policy als tabelrijen. */
const BODY_SKIP = new Set(["@odata.type", "displayName", "description", "name", "roleScopeTagIds", "settings", "platforms", "technologies", "templateReference"]);

function bodyRows(raw, prefix = "", rows = []) {
  for (const [key, value] of Object.entries(raw)) {
    if (BODY_SKIP.has(key) && !prefix) continue;
    const label = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === "object" && !Array.isArray(value)) bodyRows(value, label, rows);
    else if (Array.isArray(value)) {
      if (value.length === 0) rows.push({ id: label, value: "—" });
      else if (value.every((v) => typeof v !== "object")) rows.push({ id: label, value: value.join(", ") });
      else value.forEach((v, i) => bodyRows(v, `${label}[${i}]`, rows));
    } else rows.push({ id: label, value: value === null ? "—" : truncateScalar(String(value)) });
  }
  return rows;
}

/**
 * Losse waarden afkappen op dezelfde lengte als shortValue() bij de settings-tabellen. Een
 * custom macOS-profiel draagt zijn hele mobileconfig als base64 in `payload`; onafgekapt is dat
 * duizenden tekens in één tabelcel, en dan is de tabel eromheen niet meer te lezen. Alleen
 * scalairen: lijstwaarden (managedUniversalLinks bij App Protection) blijven volledig, want
 * daar is de inhoud van de lijst juist wat je wil zien.
 */
function truncateScalar(text) {
  return text.length > 110 ? `${text.slice(0, 107)}…` : text;
}

/**
 * De normen uit `controls` in het manifest, als tabel onder de policy. Alleen de labels: wat een
 * control betekent en wat er organisatorisch naast nodig is staat in COMPLIANCE.md, en dat hier
 * herhalen zou honderdvijftig kopieën opleveren die elk apart verouderen.
 */
const CONTROL_FRAMEWORKS = [
  ["iso", "ISO/IEC 27001:2022"],
  ["nis2", "NIS2 art. 21(2)"],
  ["cis", "CIS Controls v8.1"],
  ["nistcsf", "NIST CSF 2.0"],
];

/**
 * Een label in de taal van het document. ISO krijgt de officiële Engelse titel uit de
 * vocabulaire (`titelEn`) en in het Frans de vertaling van de NEN-titel; NIS2 gaat door het
 * woordenboek. CIS en NIST CSF zijn al Engels en blijven dat in elke taal.
 */
function controlLabel(key, label, ctx) {
  const text = String(label);
  if (key === "cis") return text.replace(/^CIS Controls v8\.1 /, "");
  if (V.lang === "nl" || key === "nistcsf") return text;
  if (key === "iso") {
    const m = text.match(/^(A\.\d+\.\d+)(?:\s|$)/);
    const c = m && ctx.isoById.get(m[1]);
    if (!c) return text;
    return `${c.id} ${V.lang === "en" ? c.titelEn : V.d(c.titelNen)}`;
  }
  return V.d(text);
}

function controlsSection(controls, ctx) {
  const rows = CONTROL_FRAMEWORKS.filter(([key]) => (controls[key] || []).length > 0).map(
    ([key, label]) => `| ${label} | ${controls[key].map((c) => escapePipes(controlLabel(key, c, ctx))).join("<br>")} |`
  );
  if (rows.length === 0) return [];
  return [
    V.t({ nl: "## Normen", en: "## Standards", fr: "## Normes" }),
    "",
    V.t({ nl: "| Kader | Controls |", en: "| Framework | Controls |", fr: "| Référentiel | Mesures |" }),
    "|---|---|",
    ...rows,
    "",
    V.t({
      nl: `Wat dit per norm betekent en wat er organisatorisch naast nodig is: [COMPLIANCE.md](${V.link("../../../docs/COMPLIANCE.md")}).`,
      en: `What this means per standard and what is needed organisationally alongside it: [COMPLIANCE.en.md](${V.link("../../../docs/COMPLIANCE.md")}).`,
      fr: `Ce que cela signifie pour chaque norme et ce qui reste nécessaire sur le plan organisationnel : [COMPLIANCE.fr.md](${V.link("../../../docs/COMPLIANCE.md")}).`,
    }),
    "",
  ];
}

/**
 * De koppeling met Conditional Access, van de Intune-kant gezien: per Intune-policy de CA-policies
 * die erop leunen. Uit de CA-Policies-repo als die ernaast staat (en dan ook als nieuwe inhoud van
 * _ca.json), anders uit _ca.json zelf.
 */
function loadCaLinks() {
  const root = CA_SIBLINGS.find((d) => fs.existsSync(path.join(d, "docs", "policies.json")) && fs.existsSync(path.join(d, "CATemplate")));
  if (!root) {
    const snapshot = fs.existsSync(CA_SNAPSHOT_PATH) ? JSON.parse(fs.readFileSync(CA_SNAPSHOT_PATH, "utf8")) : { koppelingen: {} };
    return { root: null, snapshot, content: null };
  }
  const data = JSON.parse(fs.readFileSync(path.join(root, "docs", "policies.json"), "utf8"));
  const groups = data.groepen || {};
  const koppelingen = {};
  for (const ca of Object.keys(data.policies).sort()) {
    const file = path.join(root, "CATemplate", `${ca}.json`);
    if (!fs.existsSync(file)) continue;
    const inner = JSON.parse(JSON.parse(fs.readFileSync(file, "utf8")).JSON);
    for (const link of data.policies[ca].intune || []) {
      for (const target of link.targets.flatMap((t) => (t.startsWith("@") ? groups[t.slice(1)] || [] : [t]))) {
        const baseName = path.posix.basename(target);
        const list = (koppelingen[baseName] = koppelingen[baseName] || []);
        if (!list.some((x) => x.ca === ca)) list.push({ ca, displayName: inner.displayName, state: inner.state, waarom: link.waarom });
      }
    }
  }
  const snapshot = {
    _comment: [
      "Gegenereerd door scripts/generate-docs.js uit docs/policies.json in de CA-Policies-repo — niet met de hand bijwerken.",
      "Per Intune-policy de Conditional Access-policies die erop leunen, en waarom. Een kopie, zodat de",
      "README per policy ook in CI (zonder de CA-repo ernaast) dezelfde sectie 'Conditional Access' krijgt.",
      "Wijzigen gebeurt in de CA-Policies-repo; draai daarna hier generate-docs.js met die repo ernaast.",
    ],
    koppelingen: Object.fromEntries(Object.keys(koppelingen).sort().map((k) => [k, koppelingen[k]])),
  };
  return { root, snapshot, content: JSON.stringify(snapshot, null, 2) + "\n" };
}

const CA_STATE = { enabled: "enabled", enabledForReportingButNotEnforced: "report-only", disabled: "disabled" };

function caSection(baseName, ctx) {
  const links = (ctx.ca.snapshot.koppelingen || {})[baseName] || [];
  if (links.length === 0) return [];
  return [
    "## Conditional Access",
    "",
    V.t({
      nl: `Deze Conditional Access-policies uit de [CA-Policies-repo](${CA_URL.replace(/blob\/main\/$/, "")}) leunen op deze policy. Wijzig of verwijder je hem, kijk dan eerst wat dat daar doet.`,
      en: `These Conditional Access policies from the [CA-Policies repo](${CA_URL.replace(/blob\/main\/$/, "")}) rely on this policy. Before you change or remove it, check what that does there.`,
      fr: `Ces stratégies Conditional Access du [dépôt CA-Policies](${CA_URL.replace(/blob\/main\/$/, "")}) s'appuient sur cette policy. Avant de la modifier ou de la supprimer, vérifiez l'effet là-bas.`,
    }),
    "",
    V.t({ nl: "| CA-policy | State | Wat deze policy ervoor doet |", en: "| CA policy | State | What this policy does for it |", fr: "| Stratégie CA | State | Ce que cette policy fait pour elle |" }),
    "|---|---|---|",
    ...links.map((l) => {
      const doc = V.link(`${l.ca}.md`);
      const label = l.displayName.replace(/^CXNM - STANDARD - /, "");
      return `| [${escapePipes(label)}](${CA_URL}CATemplate/${doc}) | ${CA_STATE[l.state] || l.state} | ${escapePipes(l.waarom[V.lang] || l.waarom.nl)} |`;
    }),
    "",
  ];
}

/** Hoeveel verschillende Annex A-controls de policies in fase 1 samen raken — voor OVERZICHT.md. */
function isoControlsInFase1(templates, manifestByTarget) {
  const ids = new Set();
  for (const t of templates) {
    const entry = manifestByTarget.get(t.baseName) || {};
    if (entry.fase !== 1 || !entry.controls) continue;
    for (const label of entry.controls.iso || []) {
      const m = String(label).match(/^A\.\d+\.\d+/);
      if (m) ids.add(m[0]);
    }
  }
  return ids.size;
}

function policyTable(templates, { assignments, manifestByTarget }) {
  const header = V.t({
    nl: "| Policy | Wat het doet | Type | Instellingen | Toewijzing |",
    en: "| Policy | What it does | Type | Settings | Assignment |",
    fr: "| Policy | Ce qu'elle fait | Type | Paramètres | Affectation |",
  }) + "\n|---|---|---|---:|---|";

  const rows = templates.map((t) => {
    const item = parseBaseName(t.baseName).item.replace(/_/g, " ");
    const entry = manifestByTarget.get(t.baseName);
    const doc = V.link(`${TYPE_TO_CATEGORY[t.type]}/${t.baseName}.md`);
    const cells = [
      `[**${escapePipes(item)}**](${doc})`,
      escapePipes(entry && entry.doel ? V.d(entry.doel) : "—"),
      TYPE_LABEL[t.type] || t.type,
      settingCount(t),
      assignmentLabel(assignments, t.displayName),
    ];
    return `| ${cells.join(" | ")} |`;
  });
  return [header, ...rows].join("\n");
}

/**
 * Eén markdown per policy, naast de JSON: wat de policy doet, waar hij landt, en élke
 * instelling die hij zet. De JSON is voor de tooling, dit is voor de mens die wil weten wat
 * er precies verandert vóór hij het uitrolt.
 */
function policyDocument(template, ctx) {
  const { baseName, type, displayName, raw } = template;
  const parsed = parseBaseName(baseName);
  const entry = ctx.manifestByTarget.get(baseName) || {};
  const family = raw.templateReference && raw.templateReference.templateId ? raw.templateReference.templateFamily : null;

  const lines = [
    ...head(`${baseName}.md`),
    `# ${displayName}`,
    "",
    V.d(entry.doel) || "",
    "",
    "| | |",
    "|---|---|",
    `| Platform | ${PLATFORMS[parsed.platform].label} |`,
    `| Scope | ${
      parsed.scope === "D"
        ? V.t({ nl: "Device (D) — toewijzen aan apparaatgroepen", en: "Device (D) — assign to device groups", fr: "Device (D) — affecter à des groupes d'appareils" })
        : V.t({ nl: "User (U) — toewijzen aan gebruikersgroepen", en: "User (U) — assign to user groups", fr: "User (U) — affecter à des groupes d'utilisateurs" })
    } |`,
    `| Type | ${TYPE_LABEL[type] || type}${family ? ` (${family})` : ""} |`,
    `| ${V.t({ nl: "Toewijzing", en: "Assignment", fr: "Affectation" })} | ${assignmentLabel(ctx.assignments, displayName)} |`,
    `| ${V.t({ nl: "Bron", en: "Source", fr: "Source" })} | ${entry.bron ? V.d(entry.bron) : V.t({ nl: "eigen baseline", en: "own baseline", fr: "baseline propre" })} |`,
    `| ${V.t({ nl: "Bestand", en: "File", fr: "Fichier" })} | [\`${baseName}.json\`](${baseName}.json) |`,
    "",
  ];

  // Elke regel apart voorzien van "> ": een note van meer dan één alinea zou anders na de
  // eerste lege regel uit de blockquote lopen en als losse tekst onder het kader eindigen —
  // dan lijkt de helft van de note bij de policy te horen in plaats van bij de waarschuwing.
  if (entry.note) {
    lines.push(
      V.d(entry.note)
        .split("\n")
        .map((regel) => (regel ? `> ${regel}` : ">"))
        .join("\n"),
      ""
    );
  }

  if (entry.controls) lines.push(...controlsSection(entry.controls, ctx));
  lines.push(...caSection(baseName, ctx));

  if (type === "Catalog") {
    const rows = [];
    for (const s of raw.settings || []) settingRows(s.settingInstance, 0, rows);
    lines.push(
      `${V.t({ nl: "## Instellingen", en: "## Settings", fr: "## Paramètres" })} — ${rows.filter((r) => r.id).length}`,
      "",
      ...V.t({
        nl: ["Ingesprongen regels zijn kindinstellingen: die gelden alleen als hun bovenliggende", "instelling op de getoonde waarde staat."],
        en: ["Indented rows are child settings: they only apply when their parent", "setting has the value shown."],
        fr: ["Les lignes en retrait sont des paramètres enfants : ils ne s'appliquent que si le", "paramètre parent a la valeur indiquée."],
      }),
      "",
      V.t({ nl: "| Instelling | Waarde |", en: "| Setting | Value |", fr: "| Paramètre | Valeur |" }),
      "|---|---|",
      ...rows.map((r) => {
        const indent = "&nbsp;".repeat(r.depth * 4);
        if (r.separator) return `| ${indent}*${r.separator}* | |`;
        return `| ${indent}\`${escapePipes(r.id)}\` | ${escapePipes(r.value)} |`;
      }),
      ""
    );
  } else if (type === "Admin") {
    const yes = V.t({ nl: "ja", en: "yes", fr: "oui" });
    const no = V.t({ nl: "nee", en: "no", fr: "non" });
    lines.push(
      `${V.t({ nl: "## ADMX-definities", en: "## ADMX definitions", fr: "## Définitions ADMX" })} — ${(raw.added || []).length}`,
      "",
      ...V.t({
        nl: ["Klassieke Group Policy-instellingen. De GUID's zijn Microsoft's vaste", "ADMX-catalogus-id's en dus tenant-onafhankelijk."],
        en: ["Classic Group Policy settings. The GUIDs are Microsoft's fixed", "ADMX catalogue ids and therefore tenant-independent."],
        fr: ["Paramètres de stratégie de groupe classiques. Les GUID sont les identifiants fixes du", "catalogue ADMX de Microsoft, donc indépendants du tenant."],
      }),
      "",
      V.t({ nl: "| Definitie | Ingeschakeld | Waarden |", en: "| Definition | Enabled | Values |", fr: "| Définition | Activée | Valeurs |" }),
      "|---|---|---|",
      ...(raw.added || []).map((d) => {
        const guid = (d["definition@odata.bind"] || "").match(/groupPolicyDefinitions\('([^']+)'\)/);
        const values = (d.presentationValues || []).map((p) => escapePipes(String(p.value))).join(", ") || "—";
        return `| \`${guid ? guid[1] : "?"}\` | ${d.enabled ? yes : no} | ${values} |`;
      }),
      ""
    );
  } else {
    const rows = bodyRows(raw);
    lines.push(
      `${V.t({ nl: "## Eigenschappen", en: "## Properties", fr: "## Propriétés" })} — ${rows.length}`,
      "",
      type === "deviceCompliancePolicies"
        ? V.t({
            nl: "Een compliance-policy heeft geen settingDefinitionId's maar vaste eigenschappen. `scheduledActionsForRule` bepaalt wat er gebeurt als een apparaat niet voldoet.",
            en: "A compliance policy has no settingDefinitionIds but fixed properties. `scheduledActionsForRule` determines what happens when a device does not comply.",
            fr: "Une policy de conformité n'a pas de settingDefinitionId mais des propriétés fixes. `scheduledActionsForRule` détermine ce qui se passe lorsqu'un appareil n'est pas conforme.",
          })
        : type === "AppProtection"
          ? V.t({
              nl: "Een app protection-policy heeft geen settingDefinitionId's maar vaste eigenschappen. `—` betekent niet ingesteld.",
              en: "An app protection policy has no settingDefinitionIds but fixed properties. `—` means not configured.",
              fr: "Une policy de protection d'application n'a pas de settingDefinitionId mais des propriétés fixes. `—` signifie non configuré.",
            })
          : V.t({
              nl: "Een klassieke device configuration heeft geen settingDefinitionId's maar vaste eigenschappen.",
              en: "A classic device configuration has no settingDefinitionIds but fixed properties.",
              fr: "Une configuration d'appareil classique n'a pas de settingDefinitionId mais des propriétés fixes.",
            }),
      "",
      V.t({ nl: "| Eigenschap | Waarde |", en: "| Property | Value |", fr: "| Propriété | Valeur |" }),
      "|---|---|",
      ...rows.map((r) => `| \`${escapePipes(r.id)}\` | ${escapePipes(r.value)} |`),
      ""
    );
  }

  const label = PLATFORMS[parsed.platform].label;
  lines.push(
    "---",
    "",
    V.t({
      nl: `Terug naar het [${label}-overzicht](${V.link("../README.md")}) · [hoofd-README](${V.link("../../../README.md")})`,
      en: `Back to the [${label} overview](${V.link("../README.md")}) · [main README](${V.link("../../../README.md")})`,
      fr: `Retour à la [vue d'ensemble ${label}](${V.link("../README.md")}) · [README principal](${V.link("../../../README.md")})`,
    }),
    ""
  );
  return lines.join("\n");
}

function platformReadme(platform, templates, ctx) {
  const label = PLATFORMS[platform].label;
  const byScope = { D: templates.filter((t) => parseBaseName(t.baseName).scope === "D"), U: templates.filter((t) => parseBaseName(t.baseName).scope === "U") };
  const byCategory = {};
  for (const t of templates) {
    const cat = TYPE_TO_CATEGORY[t.type];
    byCategory[cat] = (byCategory[cat] || 0) + 1;
  }

  const lines = [
    ...head("README.md"),
    `# ${label} — ${policies(templates.length)}`,
    "",
    V.t({
      nl: `Alle policies heten \`CXNM - Standard - ${platform} - <D|U> - <Item>\`; de tabellen hieronder laten het \`<Item>\`-deel zien.`,
      en: `All policies are named \`CXNM - Standard - ${platform} - <D|U> - <Item>\`; the tables below show the \`<Item>\` part.`,
      fr: `Toutes les policies s'appellent \`CXNM - Standard - ${platform} - <D|U> - <Item>\` ; les tableaux ci-dessous montrent la partie \`<Item>\`.`,
    }),
    "",
    V.t({ nl: "| Map | Aantal |", en: "| Folder | Count |", fr: "| Dossier | Nombre |" }),
    "|---|---:|",
    ...Object.entries(byCategory).map(([cat, n]) => `| \`${cat}/\` | ${n} |`),
    "",
  ];

  const components = componentRows(platform);
  if (components.length > 0) {
    lines.push(
      V.t({ nl: "## Overige onderdelen", en: "## Other components", fr: "## Autres éléments" }),
      "",
      V.t({
        nl: "Geen CIPP-policytype, dus niet in de tabellen hieronder en niet in een CIPP-pakket. Hoe elk onderdeel uitrolt, staat in zijn README.",
        en: "Not a CIPP policy type, so not in the tables below and not in a CIPP package. How each component is deployed is in its README.",
        fr: "Pas un type de stratégie CIPP, donc absent des tableaux ci-dessous et d'un package CIPP. Le mode de déploiement de chaque élément figure dans son README.",
      }),
      "",
      V.t({ nl: "| Map | Wat |", en: "| Folder | What |", fr: "| Dossier | Quoi |" }),
      "|---|---|",
      ...components,
      ""
    );
  }

  for (const [scope, list] of Object.entries(byScope)) {
    if (list.length === 0) continue;
    const heading = scope === "D" ? "Device-scoped (D)" : "User-scoped (U)";
    const assignTo =
      scope === "D"
        ? V.t({ nl: "Toewijzen aan apparaatgroepen.", en: "Assign to device groups.", fr: "Affecter à des groupes d'appareils." })
        : V.t({ nl: "Toewijzen aan gebruikersgroepen.", en: "Assign to user groups.", fr: "Affecter à des groupes d'utilisateurs." });
    lines.push(`## ${heading} — ${list.length}`, "", assignTo, "", policyTable(list, ctx), "");
  }

  lines.push(
    "---",
    "",
    ...V.t({
      nl: [
        "**Wat het doet** komt uit `doel` in [`_manifest.json`](../_manifest.json). Diezelfde zin",
        "staat in het Engels, samen met het toewijzingsdoel en de herkomst, in het `Description`-veld",
        "van het template — en dus straks in de tenant naast de policy.",
      ],
      en: [
        "**What it does** comes from `doel` in [`_manifest.json`](../_manifest.json) (translated). The same",
        "sentence sits, together with the assignment target and the origin, in the template's `Description`",
        "field — and so later in the tenant next to the policy.",
      ],
      fr: [
        "**Ce qu'elle fait** provient de `doel` dans [`_manifest.json`](../_manifest.json) (traduit). La même phrase,",
        "en anglais, figure avec la cible d'affectation et l'origine dans le champ `Description` du",
        "template — et donc plus tard dans le tenant, à côté de la policy.",
      ],
    }),
    ""
  );
  return lines.join("\n");
}

/**
 * De mappen naast de CIPP-templates: inschrijving, scripts, apps, app-configuratie. Die
 * onderdelen zijn geen CIPP-policytype en rollen anders uit, maar horen wel bij het platform.
 * Elke map (of submap, bij meer onderwerpen in één onderdeel) heeft een eigen README; de
 * titel daarvan is de omschrijving hier, zodat deze tabel niet met de hand hoeft te worden
 * bijgehouden.
 */
function componentRows(platform) {
  const categories = new Set(Object.values(TYPE_TO_CATEGORY));
  const dir = path.join(TEMPLATE_DIR, platform);
  const suffix = V.lang === "nl" ? "" : `.${V.lang}`;
  const title = (readmeDir) => {
    const file = [path.join(readmeDir, `README${suffix}.md`), path.join(readmeDir, "README.md")].find((f) => fs.existsSync(f));
    if (!file) return null;
    const h1 = fs.readFileSync(file, "utf8").split(/\r?\n/).find((l) => l.startsWith("# "));
    return h1 ? h1.slice(2).trim() : "";
  };
  const rows = [];
  const areas = fs.readdirSync(dir, { withFileTypes: true }).filter((e) => e.isDirectory() && !categories.has(e.name)).map((e) => e.name).sort();
  for (const area of areas) {
    const areaDir = path.join(dir, area);
    const own = title(areaDir);
    if (own !== null) rows.push(`| [\`${area}/\`](${V.link(`${area}/README.md`)}) | ${own} |`);
    const subs = fs.readdirSync(areaDir, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name).sort();
    for (const sub of subs) {
      const t = title(path.join(areaDir, sub));
      if (t !== null) rows.push(`| [\`${area}/${sub}/\`](${V.link(`${area}/${sub}/README.md`)}) | ${t} |`);
    }
  }
  return rows;
}

/** De toewijzingstekst uit lib/templates.js; alleen de Nederlandse delen ervan vertalen. */
function packageAssignment(text) {
  if (text === "wordt niet uitgerold") return V.t({ nl: text, en: "not deployed", fr: "non déployé" });
  if (text === "Do not assign (koppelen aan een ADE-token in Intune)") {
    return V.t({ nl: text, en: "Do not assign (link to an ADE token in Intune)", fr: "Do not assign (à lier à un jeton ADE dans Intune)" });
  }
  return text;
}

function overviewReadme(templates, ctx) {
  const platforms = ["WIN", "MAC", "IOS", "AND"];
  const types = Object.keys(TYPE_LABEL);
  const total = V.t({ nl: "Totaal", en: "Total", fr: "Total" });

  const matrix = platforms.map((p) => {
    const list = templates.filter((t) => parseBaseName(t.baseName).platform === p);
    if (list.length === 0) return null;
    const counts = types.map((ty) => list.filter((t) => t.type === ty).length);
    return `| [${PLATFORMS[p].label}](${V.link(`${p}/README.md`)}) | ${counts.map((c) => (c === 0 ? "–" : c)).join(" | ")} | **${list.length}** |`;
  }).filter(Boolean);

  const totals = types.map((ty) => templates.filter((t) => t.type === ty).length);

  return [
    ...head("README.md"),
    `# IntuneTemplate — ${policies(templates.length)}`,
    "",
    ...V.t({
      nl: ["De bron van deze repo: de afgesproken Intune-policies in CIPP-templateformaat. Alles wat", "in `export/` en `BaselineTemplate/` staat is hieruit afgeleid en wordt gegenereerd."],
      en: ["The source of this repo: the agreed Intune policies in CIPP template format. Everything", "in `export/` and `BaselineTemplate/` is derived from it and generated."],
      fr: ["La source de ce dépôt : les policies Intune convenues, au format template CIPP. Tout ce qui", "se trouve dans `export/` et `BaselineTemplate/` en est dérivé et généré."],
    }),
    "",
    `| Platform | ${types.map((t) => TYPE_LABEL[t]).join(" | ")} | ${total} |`,
    `|---|${types.map(() => "---:").join("|")}|---:|`,
    ...matrix,
    `| **${total}** | ${totals.map((c) => `**${c || "–"}**`).join(" | ")} | **${templates.length}** |`,
    "",
    V.t({ nl: "## Indeling", en: "## Layout", fr: "## Organisation" }),
    "",
    "```mermaid",
    "flowchart LR",
    "  T[IntuneTemplate/] --> WIN[WIN/]",
    "  T --> MAC[MAC/]",
    "  T --> IOS[IOS/]",
    "  T --> AND[AND/]",
    "  WIN --> WSC[SettingsCatalog/]",
    "  WIN --> WAT[AdministrativeTemplates/]",
    "  WIN --> WDC[DeviceConfigurations/]",
    "  WIN --> WCP[CompliancePolicies/]",
    "  MAC --> MSC[SettingsCatalog/]",
    "  MAC --> MCP[CompliancePolicies/]",
    "  IOS --> IAP[AppProtection/]",
    "  AND --> AAP[AppProtection/]",
    "```",
    "",
    ...V.t({
      nl: [
        "De map volgt uit de bestandsnaam (platform) en het CIPP-`Type` (policytype) en draagt dus",
        "geen informatie die niet ook in het bestand staat. `check-scope.js` controleert dat elk",
        "bestand op zijn plek staat.",
      ],
      en: [
        "The folder follows from the file name (platform) and the CIPP `Type` (policy type), so it carries",
        "no information that is not also in the file. `check-scope.js` checks that every",
        "file is in its place.",
      ],
      fr: [
        "Le dossier découle du nom de fichier (plateforme) et du `Type` CIPP (type de policy) ; il ne porte donc",
        "aucune information qui ne figure pas déjà dans le fichier. `check-scope.js` vérifie que chaque",
        "fichier est à sa place.",
      ],
    }),
    "",
    ...V.t({
      nl: [
        "Naast die policytype-mappen heeft elk platform mappen voor wat geen CIPP-policytype is, ingedeeld",
        "zoals de menu's van de Intune-portal: `Enrollment/`, `EndpointSecurity/`, `PlatformScripts/`,",
        "`Remediations/`, `ComplianceScripts/`, `Apps/`, `AppConfiguration/` en `AssignmentFilters/`. De",
        "platform-README somt ze op onder *Overige onderdelen*; de pijplijn leest ze niet.",
      ],
      en: [
        "Next to those policy type folders, each platform has folders for what is not a CIPP policy type,",
        "organised like the menus of the Intune portal: `Enrollment/`, `EndpointSecurity/`, `PlatformScripts/`,",
        "`Remediations/`, `ComplianceScripts/`, `Apps/`, `AppConfiguration/` and `AssignmentFilters/`. The",
        "platform README lists them under *Other components*; the pipeline does not read them.",
      ],
      fr: [
        "À côté de ces dossiers par type de policy, chaque plateforme a des dossiers pour ce qui n'est pas un",
        "type de policy CIPP, organisés comme les menus du portail Intune : `Enrollment/`, `EndpointSecurity/`,",
        "`PlatformScripts/`, `Remediations/`, `ComplianceScripts/`, `Apps/`, `AppConfiguration/` et",
        "`AssignmentFilters/`. Le README de la plateforme les liste sous *Autres éléments* ; le pipeline ne les lit pas.",
      ],
    }),
    "",
    V.t({ nl: "## De `_`-bestanden", en: "## The `_` files", fr: "## Les fichiers `_`" }),
    "",
    V.t({ nl: "| Bestand | Wat het vastlegt | Gelezen door |", en: "| File | What it records | Read by |", fr: "| Fichier | Ce qu'il consigne | Lu par |" }),
    "|---|---|---|",
    V.t({
      nl: "| [`_assignments.json`](_assignments.json) | het toewijzingsdoel per policy | `export-intunebackup.js`, `check-scope.js` |",
      en: "| [`_assignments.json`](_assignments.json) | the assignment target per policy | `export-intunebackup.js`, `check-scope.js` |",
      fr: "| [`_assignments.json`](_assignments.json) | la cible d'affectation par policy | `export-intunebackup.js`, `check-scope.js` |",
    }),
    V.t({
      nl: "| [`_manifest.json`](_manifest.json) | welke OIB-policy waar landt, waarom er afgeweken wordt en in welke fase hij uitrolt | `import-oib.js`, `set-packages.js` |",
      en: "| [`_manifest.json`](_manifest.json) | which OIB policy lands where, why it deviates and in which phase it is deployed | `import-oib.js`, `set-packages.js` |",
      fr: "| [`_manifest.json`](_manifest.json) | quelle policy OIB atterrit où, pourquoi il y a un écart et dans quelle phase elle est déployée | `import-oib.js`, `set-packages.js` |",
    }),
    V.t({
      nl: "| [`_renames.json`](_renames.json) | hoe policies in de tenant heetten en wat er nu bij hoort | `Rename-BaselinePolicy.ps1`, `check-scope.js` |",
      en: "| [`_renames.json`](_renames.json) | what policies were called in the tenant and what they map to now | `Rename-BaselinePolicy.ps1`, `check-scope.js` |",
      fr: "| [`_renames.json`](_renames.json) | le nom des policies dans le tenant et leur correspondance actuelle | `Rename-BaselinePolicy.ps1`, `check-scope.js` |",
    }),
    V.t({
      nl: "| [`_ca.json`](_ca.json) | per policy de Conditional Access-policies die erop leunen — een kopie uit `docs/policies.json` in de CA-Policies-repo | `generate-docs.js` (schrijft hem ook, met die repo ernaast) |",
      en: "| [`_ca.json`](_ca.json) | per policy the Conditional Access policies that rely on it — a copy from `docs/policies.json` in the CA-Policies repo | `generate-docs.js` (also writes it, with that repo next to this one) |",
      fr: "| [`_ca.json`](_ca.json) | par policy les stratégies Conditional Access qui s'appuient sur elle — une copie de `docs/policies.json` du dépôt CA-Policies | `generate-docs.js` (l'écrit aussi, avec ce dépôt à côté) |",
    }),
    V.t({
      nl: "| [`_controls.json`](_controls.json) | de normenvocabulaire: ISO 27001 Annex A, NIS2 art. 21(2), CIS Controls v8.1, NIST CSF 2.0 | `check-scope.js`, `generate-compliance.js` |",
      en: "| [`_controls.json`](_controls.json) | the standards vocabulary: ISO 27001 Annex A, NIS2 art. 21(2), CIS Controls v8.1, NIST CSF 2.0 | `check-scope.js`, `generate-compliance.js` |",
      fr: "| [`_controls.json`](_controls.json) | le vocabulaire des normes : ISO 27001 Annexe A, NIS2 art. 21(2), CIS Controls v8.1, NIST CSF 2.0 | `check-scope.js`, `generate-compliance.js` |",
    }),
    V.t({
      nl: "| [`_i18n/`](_i18n/) | de Engelse en Franse vertaling van de teksten uit de data, voor de gegenereerde documentatie | `generate-docs.js`, `generate-compliance.js` |",
      en: "| [`_i18n/`](_i18n/) | the English and French translation of the texts from the data, for the generated documentation | `generate-docs.js`, `generate-compliance.js` |",
      fr: "| [`_i18n/`](_i18n/) | la traduction anglaise et française des textes issus des données, pour la documentation générée | `generate-docs.js`, `generate-compliance.js` |",
    }),
    "",
    ...V.t({
      nl: [
        "Assignments staan bewust niet in het template zelf: CIPP wijst apart toe, maar",
        "IntuneBackupAndRestore heeft ze wél nodig om compleet terug te kunnen zetten.",
        "",
        "Ze hebben geen `RowKey` en geen `Displayname`, dus CIPP maakt er bij een repo-sync één",
        `naamloze rij van. Die doet niets — zie de [hoofd-README](${V.link("../README.md")}#${ANCHOR.restore.nl}).`,
      ],
      en: [
        "Assignments are deliberately not in the template itself: CIPP assigns separately, but",
        "IntuneBackupAndRestore does need them to restore completely.",
        "",
        "They have no `RowKey` and no `Displayname`, so on a repo sync CIPP turns them into one",
        `nameless row. It does nothing — see the [main README](${V.link("../README.md")}#${ANCHOR.restore.en}).`,
      ],
      fr: [
        "Les affectations ne sont volontairement pas dans le template lui-même : CIPP affecte séparément, mais",
        "IntuneBackupAndRestore en a besoin pour une restauration complète.",
        "",
        "Ils n'ont ni `RowKey` ni `Displayname` ; lors d'une synchronisation du dépôt, CIPP en fait donc une",
        `ligne sans nom. Elle ne fait rien — voir le [README principal](${V.link("../README.md")}#${ANCHOR.restore.fr}).`,
      ],
    }),
    "",
    V.t({ nl: "## CIPP-pakketten", en: "## CIPP packages", fr: "## Packages CIPP" }),
    "",
    ...V.t({
      nl: [
        "Het veld `Package` in elk template. CIPP's baselines kennen de standard **Intune Template",
        "Package**: die rolt in één keer élk template met dezelfde waarde uit en bepaalt dat",
        "lidmaatschap bij iedere run opnieuw — een nieuwe policy schuift dus vanzelf mee, zonder dat",
        "er in CIPP iets aangeklikt hoeft te worden.",
        "",
        "De deploy-opties van die ene standard worden letterlijk op elk lid gekopieerd, dus één",
        "pakket is één toewijzingsdoel. Vandaar de verdeling hieronder in plaats van `Baseline` op",
        "alles: die zou de gebruikerspolicies op apparaten zetten en de policies die nog niet klaar",
        "zijn ongetest uitrollen. De waarde volgt uit `fase` in `_manifest.json` en het doel in",
        "`_assignments.json`; `set-packages.js` schrijft hem, `check-scope.js` bewaakt hem.",
      ],
      en: [
        "The `Package` field in every template. CIPP's baselines have the standard **Intune Template",
        "Package**: it deploys every template with the same value in one go and re-evaluates that",
        "membership on every run — so a new policy moves along automatically, without anything",
        "having to be clicked in CIPP.",
        "",
        "The deploy options of that one standard are copied literally onto every member, so one",
        "package is one assignment target. Hence the split below instead of `Baseline` on",
        "everything: that would put the user policies on devices and deploy the policies that are not",
        "ready yet untested. The value follows from `fase` in `_manifest.json` and the target in",
        "`_assignments.json`; `set-packages.js` writes it, `check-scope.js` guards it.",
      ],
      fr: [
        "Le champ `Package` de chaque template. Les baselines de CIPP disposent du standard **Intune Template",
        "Package** : il déploie en une fois chaque template portant la même valeur et réévalue cette",
        "appartenance à chaque exécution — une nouvelle policy suit donc automatiquement, sans rien",
        "avoir à cliquer dans CIPP.",
        "",
        "Les options de déploiement de ce standard sont copiées telles quelles sur chaque membre : un",
        "package correspond donc à une cible d'affectation. D'où la répartition ci-dessous plutôt que `Baseline`",
        "partout : cela appliquerait les policies utilisateur aux appareils et déploierait sans test les policies",
        "qui ne sont pas encore prêtes. La valeur découle de `fase` dans `_manifest.json` et de la cible dans",
        "`_assignments.json` ; `set-packages.js` l'écrit, `check-scope.js` la contrôle.",
      ],
    }),
    "",
    V.t({
      nl: "| `Package` | In CIPP toewijzen aan | Stage | Policies |",
      en: "| `Package` | Assign in CIPP to | Stage | Policies |",
      fr: "| `Package` | Affecter dans CIPP à | Stage | Policies |",
    }),
    "|---|---|---:|---:|",
    ...packagePlan(ctx.manifest, ctx.assignments).map(
      (p) => `| ${p.pakket ? `\`${p.pakket}\`` : V.t({ nl: "*(leeg)*", en: "*(empty)*", fr: "*(vide)*" })} | ${packageAssignment(p.toewijzing)} | ${p.stage ?? "–"} | ${p.leden.length} |`
    ),
    "",
    ...V.t({
      nl: [
        "De stage-kolom is de stage in [`BaselineTemplate/Baseline.json`](../BaselineTemplate/Baseline.json),",
        "de CIPP-baseline die deze pakketten uitrolt.",
        "",
        "Fase 5 krijgt bewust een lege waarde: CIPP toont alleen pakketten met een gevulde",
        "`Package`, dus die policies staan in geen enkel pakket. Los kiezen kan nog steeds — ze",
        "bestaan als alternatief voor een policy die wél uitrolt.",
      ],
      en: [
        "The stage column is the stage in [`BaselineTemplate/Baseline.json`](../BaselineTemplate/Baseline.json),",
        "the CIPP baseline that deploys these packages.",
        "",
        "Phase 5 deliberately gets an empty value: CIPP only shows packages with a filled-in",
        "`Package`, so those policies are in no package at all. They can still be picked individually —",
        "they exist as an alternative to a policy that is deployed.",
      ],
      fr: [
        "La colonne stage est le stage dans [`BaselineTemplate/Baseline.json`](../BaselineTemplate/Baseline.json),",
        "la baseline CIPP qui déploie ces packages.",
        "",
        "La phase 5 reçoit volontairement une valeur vide : CIPP n'affiche que les packages dont le `Package`",
        "est renseigné, ces policies ne figurent donc dans aucun package. On peut toujours les choisir une à une —",
        "elles existent comme alternative à une policy qui, elle, est déployée.",
      ],
    }),
    "",
    V.t({ nl: "## Per platform", en: "## Per platform", fr: "## Par plateforme" }),
    "",
    ...platforms.filter((p) => templates.some((t) => parseBaseName(t.baseName).platform === p)).map((p) => {
      const n = templates.filter((t) => parseBaseName(t.baseName).platform === p).length;
      return `- [${PLATFORMS[p].label}](${V.link(`${p}/README.md`)}) — ${policies(n)}`;
    }),
    "",
    ...V.t({
      nl: [`Zie de [hoofd-README](${V.link("../README.md")}) voor de naamconventie, de controles en hoe je een`, "nieuwe OpenIntuneBaseline-versie binnenhaalt."],
      en: [`See the [main README](${V.link("../README.md")}) for the naming convention, the checks and how to bring in a`, "new OpenIntuneBaseline version."],
      fr: [`Voir le [README principal](${V.link("../README.md")}) pour la convention de nommage, les contrôles et la façon d'intégrer une`, "nouvelle version d'OpenIntuneBaseline."],
    }),
    "",
  ].join("\n");
}

/**
 * OVERZICHT.md: de samenvatting om te presenteren. De tellingen worden berekend, de rest is
 * vaste tekst — die beschrijft een moment (wat er in augustus 2026 veranderd is) en veroudert
 * dus niet zoals een telling dat doet.
 */
function overviewDocument(templates, ctx) {
  const platforms = ["WIN", "MAC", "IOS", "AND"];
  const types = Object.keys(TYPE_LABEL);
  const perPlatform = (p) => templates.filter((t) => parseBaseName(t.baseName).platform === p);
  const unassigned = templates.filter((t) => !ctx.assignments[t.displayName]);
  // De pilottabel komt uit `fase` en `faseWaarom`. Tot september 2026 stond hij hier als vaste
  // tekst, en die liep uit de pas: negen van de tien policies erin stonden in fase 1 en rolden
  // via CXNM - Standard - Baseline-Devices gewoon naar alle apparaten.
  const faseOf = (t) => (ctx.manifestByTarget.get(t.baseName) || {}).fase;
  const byFase = (n) => templates.filter((t) => faseOf(t) === n).length;
  const platformRank = (t) => platforms.indexOf(parseBaseName(t.baseName).platform);
  const pilot = templates
    .filter((t) => faseOf(t) === 2)
    .sort((a, b) => platformRank(a) - platformRank(b) || a.displayName.localeCompare(b.displayName))
    .map((t) => ctx.manifestByTarget.get(t.baseName));

  const matrix = platforms
    .map((p) => {
      const list = perPlatform(p);
      if (list.length === 0) return null;
      const counts = types.map((ty) => list.filter((t) => t.type === ty).length);
      return `| [${PLATFORMS[p].label}](${V.link(`../IntuneTemplate/${p}/README.md`)}) | ${counts.map((c) => (c === 0 ? "–" : c)).join(" | ")} | **${list.length}** |`;
    })
    .filter(Boolean);

  const nPlatforms = platforms.filter((p) => perPlatform(p).length > 0).length;
  const withControls = templates.filter((t) => (ctx.manifestByTarget.get(t.baseName) || {}).controls).length;
  const isoFase1 = isoControlsInFase1(templates, ctx.manifestByTarget);
  const count = V.t({ nl: "Aantal", en: "Count", fr: "Nombre" });

  return [
    ...head("OVERZICHT.md"),
    V.t({ nl: "# Intune-baseline — overzicht", en: "# Intune baseline — overview", fr: "# Baseline Intune — vue d'ensemble" }),
    "",
    ...V.t({
      nl: [
        `${templates.length} policies over ${nPlatforms} platformen, met`,
        "[OpenIntuneBaseline](https://github.com/SkipToTheEndpoint/OpenIntuneBaseline) als bron.",
        `Dit is de samenvatting; de details staan in de [hoofd-README](${V.link("../README.md")}) en per map.`,
      ],
      en: [
        `${templates.length} policies across ${nPlatforms} platforms, with`,
        "[OpenIntuneBaseline](https://github.com/SkipToTheEndpoint/OpenIntuneBaseline) as the source.",
        `This is the summary; the details are in the [main README](${V.link("../README.md")}) and per folder.`,
      ],
      fr: [
        `${templates.length} policies sur ${nPlatforms} plateformes, avec`,
        "[OpenIntuneBaseline](https://github.com/SkipToTheEndpoint/OpenIntuneBaseline) comme source.",
        `Ceci est le résumé ; les détails se trouvent dans le [README principal](${V.link("../README.md")}) et dans chaque dossier.`,
      ],
    }),
    "",
    `| | ${count} |`,
    "|---|---:|",
    `| Policies | ${templates.length} |`,
    `| ${V.t({ nl: "Zonder toewijzing (bewust)", en: "Without assignment (deliberately)", fr: "Sans affectation (volontairement)" })} | ${unassigned.length} |`,
    `| ${V.t({ nl: "Uitgerold in de tenant", en: "Deployed in the tenant", fr: "Déployées dans le tenant" })} | 0 |`,
    "",
    V.t({ nl: "## Wat er in zit", en: "## What is in it", fr: "## Contenu" }),
    "",
    `| Platform | ${types.map((t) => TYPE_LABEL[t]).join(" | ")} | ${V.t({ nl: "Totaal", en: "Total", fr: "Total" })} |`,
    `|---|${types.map(() => "---:").join("|")}|---:|`,
    ...matrix,
    "",
    V.t({
      nl: "Per platform staat er een tabel met **elke policy, wat hij doet en waar hij landt**:",
      en: "Each platform has a table with **every policy, what it does and where it lands**:",
      fr: "Chaque plateforme dispose d'un tableau avec **chaque policy, ce qu'elle fait et où elle atterrit** :",
    }),
    ...platforms.filter((p) => perPlatform(p).length > 0).map((p) => `- [${PLATFORMS[p].label}](${V.link(`../IntuneTemplate/${p}/README.md`)}) — ${policies(perPlatform(p).length)}`),
    "",
    V.t({ nl: "## Normenkader", en: "## Compliance framework", fr: "## Référentiel de conformité" }),
    "",
    ...V.t({
      nl: [
        `${withControls} van de ${templates.length} policies verwijzen naar ISO/IEC 27001:2022 Annex A, NIS2 art. 21(2),`,
        `CIS Controls v8.1 en NIST CSF 2.0; de policies in fase 1 raken samen ${isoFase1} van de 93 Annex A-controls.`,
        "Per control en per NIS2-punt wat de baseline afdwingt, hoe het getoetst wordt en wat de organisatie",
        `zelf moet regelen: [COMPLIANCE.md](${V.link("COMPLIANCE.md")}).`,
      ],
      en: [
        `${withControls} of the ${templates.length} policies reference ISO/IEC 27001:2022 Annex A, NIS2 art. 21(2),`,
        `CIS Controls v8.1 and NIST CSF 2.0; together the policies in phase 1 touch ${isoFase1} of the 93 Annex A controls.`,
        "Per control and per NIS2 point what the baseline enforces, how it is verified and what the organisation",
        `has to arrange itself: [COMPLIANCE.en.md](${V.link("COMPLIANCE.md")}).`,
      ],
      fr: [
        `${withControls} des ${templates.length} policies renvoient à l'ISO/IEC 27001:2022 Annexe A, à NIS2 art. 21(2),`,
        `aux CIS Controls v8.1 et au NIST CSF 2.0 ; ensemble, les policies de la phase 1 couvrent ${isoFase1} des 93 mesures de l'Annexe A.`,
        "Par mesure et par point NIS2 : ce que la baseline impose, comment c'est vérifié et ce que l'organisation",
        `doit régler elle-même : [COMPLIANCE.fr.md](${V.link("COMPLIANCE.md")}).`,
      ],
    }),
    "",
    V.t({ nl: "## Eén bron, twee afgeleiden", en: "## One source, two derivatives", fr: "## Une source, deux dérivés" }),
    "",
    "```mermaid",
    "flowchart LR",
    '  OIB["OpenIntuneBaseline"] -->|import-oib.js| T',
    V.t({ nl: '  T["<b>IntuneTemplate/</b><br/>de bron"]', en: '  T["<b>IntuneTemplate/</b><br/>the source"]', fr: '  T["<b>IntuneTemplate/</b><br/>la source"]' }),
    '  T -->|export-intunebackup.js| EX["export/NativeImport/<br/>IntuneBackupAndRestore/"]',
    V.t({ nl: "  T -.->|leest rechtstreeks| CIPP[CIPP]", en: "  T -.->|reads directly| CIPP[CIPP]", fr: "  T -.->|lit directement| CIPP[CIPP]" }),
    V.t({
      nl: '  EX -->|Start-IntuneRestoreConfig| TENANT[("Intune-tenant")]',
      en: '  EX -->|Start-IntuneRestoreConfig| TENANT[("Intune tenant")]',
      fr: '  EX -->|Start-IntuneRestoreConfig| TENANT[("Tenant Intune")]',
    }),
    "  CIPP --> TENANT",
    "  style T stroke-width:3px",
    "```",
    "",
    V.t({
      nl: "Wijzigen doe je in `IntuneTemplate/`. De rest wordt gegenereerd en door CI opnieuw gebouwd.",
      en: "Changes are made in `IntuneTemplate/`. The rest is generated and rebuilt by CI.",
      fr: "Les modifications se font dans `IntuneTemplate/`. Le reste est généré et reconstruit par la CI.",
    }),
    "",
    ...V.t({
      nl: [
        "## Wat er in augustus 2026 veranderde",
        "",
        "Van 24 eigen policies naar de huidige set.",
        "",
        "| | Aantal | |",
        "|---|---:|---|",
        "| Herschreven op OIB-inhoud | 15 | Edge Security ging van 2 naar 54 instellingen, Defender Antivirus van 11 naar 28, Audit van 23 naar 40 |",
        "| Nieuw | 75 | o.a. Windows Hello for Business, Credential Guard, Local Administrators, Office Security, 7 compliance-policies, 20 macOS-policies, 2 BYOD-MAM |",
        "| Opgegaan in een andere policy | 6 | Administrative Templates (300 instellingen) uit elkaar getrokken; Network Security, System Services, Windows Search en OneDrive KFM opgeslokt |",
        "| Ongewijzigd meegegaan | 5 | waar OIB geen tegenhanger voor heeft: EDR-onboarding, Outlook-autoconfiguratie, Edge-zoekmachine, update-ring 3, user experience |",
        "",
        "Instellingen die alleen de eigen baseline had — versleuteling van vaste en verwisselbare",
        "schijven bijvoorbeeld — zijn bij een herschrijving behouden in plaats van stilzwijgend",
        "weggevallen.",
        "",
        "## Wat de vergelijking met IntuneAdmin opleverde",
        "",
        "Eind augustus 2026 is de set naast [IntuneAdmin/IntuneBaselines](https://github.com/IntuneAdmin/IntuneBaselines)",
        "gelegd — 874 profielen, vergeleken op settingDefinitionId en waarde. 654 instellingen komen in",
        "beide sets voor, waarvan 55 met een andere waarde. Dat leverde vier nieuwe policies en drie",
        "aanpassingen op:",
        "",
        "| | |",
        "|---|---|",
        "| `WIN - D - Windows AI` | Recall en Click To Do uit. OIB v4.0 kent nog geen Windows AI-policy, en de baseline had er daardoor ook geen. |",
        "| `WIN - D - Removable Storage` | schrijven naar USB-opslag en WPD-apparaten geblokkeerd; verwisselbare media was nergens beperkt. |",
        "| `WIN - U - Windows Hello for Business` | WHfB per gebruiker naast de bestaande per-apparaatpolicy. |",
        "| `WIN - D - Windows Hello for Business Multi User` | WHfB voor gedeelde apparaten, zonder inrichting direct na het aanmelden. |",
        "| `WIN - D - Windows Firewall` | *local policy merge* stond alleen op het openbare profiel; nu ook op domein en privé. |",
        "| `WIN - D - Login and Lock Screen` | het wachtwoord-onthulknopje gaat uit — de enige harde CIS-L1-afwijking zonder functionele reden. |",
        "| `WIN - D - Defender Antivirus` | lage en gemiddelde dreigingen naar quarantaine in plaats van block en remove: een fout-positief is dan terug te draaien. |",
        "",
        "Daarnaast verloren de drie CIPP-standaardtemplates voor Defender hun toewijzing. Ze zetten",
        "dezelfde instellingen als hun OIB-tegenhanger op een andere waarde — 19 conflicten in totaal,",
        "waarvan 16 ASR-regels. Bij een conflict past Intune de instelling door géén van beide policies",
        "toe, dus die 16 regels stonden feitelijk uit.",
        "",
        "Wat bewust anders blijft dan CIS en IntuneAdmin: telemetrie op *Optioneel* (Endpoint Analytics",
        "en Windows Update-rapportage leunen erop) en locatie aan (Apparaat zoeken, tijdzone). Beide",
        "staan met reden in het `doel`-veld van hun policy.",
        "",
        "## Wat de macOS-herziening opleverde",
        "",
        "Eind augustus 2026 is de macOS-set als geheel nagelopen. Dat leverde twee nieuwe policies",
        "en drie correcties op:",
        "",
        "| | |",
        "|---|---|",
        "| `MAC - D - Enrollment Profile Administrator / Standard User Affinity` | twee ADE-inschrijfprofielen die in precies één instelling verschillen: wordt het aangemelde account beheerder of standaardgebruiker. Alternatieven van elkaar, dus geen van beide toegewezen. |",
        "| `MAC - D - Software Updates` | van de klassieke `com.apple.softwareupdate`-payload naar declaratief updatebeleid (DDM, macOS 14+): uitstel van 7 dagen voor kleine, 14 voor grote en 21 voor systeemupdates, Rapid Security Responses aan inclusief terugdraaien. |",
        "| `MAC - D - Defender for Endpoint` | de organisatienaam van het inhoudsfilter stond op *JAMF Software* — een restant uit de Jamf-profielen waar de MDE-documentatie op leunt. Die naam ziet de gebruiker in Systeeminstellingen → Netwerk → Filters. |",
        "| `MAC - U - Compliance Device Health` en `Device Security` | droegen elkaars omschrijving. Device Health toetst System Integrity Protection; Device Security toetst de versleuteling, de firewall en Gatekeeper. |",
        "",
        "Één gat is bewust niet gedicht: `MAC - U - Compliance Password` eist een wachtwoord van",
        "minimaal acht tekens met vergrendeling na vijftien minuten, maar er is geen configuratiepolicy",
        "die dat op de Mac instelt. Een Mac zonder schermvergrendeling wordt dus wel als niet-compliant",
        "gemeld en krijgt de instelling niet opgelegd — dat vraagt een eigen passcode-policy.",
        "",
        "## Wat er nog moet gebeuren",
        "",
        "De repo is klaar en de controles staan groen. De tenant is niet aangeraakt: de policies",
        "staan daar nog onder hun oude naam. De volgorde is een afhankelijkheid, geen suggestie —",
        "stap 4 vóór stap 3 levert twee policies op die elkaar tegenspreken.",
        "",
        "| # | Stap | |",
        "|---:|---|---|",
        "| 1 | Inventariseren | `Get-BaselinePolicyState.ps1` — moet nog gebouwd worden |",
        "| 2 | Hernoemen | `Rename-BaselinePolicy.ps1 -WhatIf` eerst; PATCH, dus id en assignments blijven |",
        "| 3 | Vervangen | Windows Firewall en Office Updates wisselen van policytype — handwerk |",
        "| 4 | Opheffen | Network Security, Windows Search, System Services, OneDrive KFM verwijderen |",
        "| 5 | Uitrollen | de nieuwe policies via CIPP of `Start-IntuneRestoreConfig` |",
        "| 6 | Toewijzen | `Set-BaselineAssignment.ps1 -Scope D -AllDevices` en `-Scope U -AllUsers` nemen alleen fase 1; de pilot volgt met `-GroupName 'SEC-Baseline-Pilot'` |",
        "| 7 | Opnieuw inventariseren | de lijst met wees-policies moet leeg zijn |",
        "",
        "## Eerst in een pilot",
        "",
        "Fase 2 in `_manifest.json`. Deze policies rollen via het pakket `CXNM - Standard - Baseline-Pilot` uit naar",
        "`SEC-Baseline-Pilot`, en pas naar iedereen als ze naar fase 1 gaan — een PR, want dat",
        "verandert naar wie ze uitrollen. Het waarom per policy is de `faseWaarom` uit het manifest.",
        "",
        "| Policy | Waarom |",
      ],
      en: [
        "## What changed in August 2026",
        "",
        "From 24 in-house policies to the current set.",
        "",
        "| | Count | |",
        "|---|---:|---|",
        "| Rewritten on OIB content | 15 | Edge Security went from 2 to 54 settings, Defender Antivirus from 11 to 28, Audit from 23 to 40 |",
        "| New | 75 | including Windows Hello for Business, Credential Guard, Local Administrators, Office Security, 7 compliance policies, 20 macOS policies, 2 BYOD MAM |",
        "| Merged into another policy | 6 | Administrative Templates (300 settings) split up; Network Security, System Services, Windows Search and OneDrive KFM absorbed |",
        "| Carried over unchanged | 5 | where OIB has no counterpart: EDR onboarding, Outlook autoconfiguration, Edge search engine, update ring 3, user experience |",
        "",
        "Settings that only the own baseline had — encryption of fixed and removable drives,",
        "for example — were kept during a rewrite instead of silently",
        "disappearing.",
        "",
        "## What the comparison with IntuneAdmin produced",
        "",
        "At the end of August 2026 the set was laid next to [IntuneAdmin/IntuneBaselines](https://github.com/IntuneAdmin/IntuneBaselines)",
        "— 874 profiles, compared on settingDefinitionId and value. 654 settings appear in",
        "both sets, 55 of them with a different value. That produced four new policies and three",
        "adjustments:",
        "",
        "| | |",
        "|---|---|",
        "| `WIN - D - Windows AI` | Recall and Click To Do off. OIB v4.0 has no Windows AI policy yet, so the baseline did not have one either. |",
        "| `WIN - D - Removable Storage` | writing to USB storage and WPD devices blocked; removable media was not restricted anywhere. |",
        "| `WIN - U - Windows Hello for Business` | WHfB per user alongside the existing per-device policy. |",
        "| `WIN - D - Windows Hello for Business Multi User` | WHfB for shared devices, without provisioning right after sign-in. |",
        "| `WIN - D - Windows Firewall` | *local policy merge* was only set on the public profile; now also on domain and private. |",
        "| `WIN - D - Login and Lock Screen` | the password reveal button is turned off — the only hard CIS L1 deviation without a functional reason. |",
        "| `WIN - D - Defender Antivirus` | low and medium threats to quarantine instead of block and remove: a false positive can then be reverted. |",
        "",
        "In addition, the three CIPP standard templates for Defender lost their assignment. They set",
        "the same settings as their OIB counterpart to a different value — 19 conflicts in total,",
        "16 of them ASR rules. On a conflict Intune applies the setting from neither policy,",
        "so those 16 rules were effectively off.",
        "",
        "What deliberately stays different from CIS and IntuneAdmin: telemetry on *Optional* (Endpoint Analytics",
        "and Windows Update reporting rely on it) and location on (Find my device, time zone). Both",
        "are explained in the `doel` field of their policy.",
        "",
        "## What the macOS review produced",
        "",
        "At the end of August 2026 the macOS set was reviewed as a whole. That produced two new policies",
        "and three corrections:",
        "",
        "| | |",
        "|---|---|",
        "| `MAC - D - Enrollment Profile Administrator / Standard User Affinity` | two ADE enrolment profiles that differ in exactly one setting: whether the signed-in account becomes administrator or standard user. Alternatives to each other, so neither is assigned. |",
        "| `MAC - D - Software Updates` | from the classic `com.apple.softwareupdate` payload to declarative update management (DDM, macOS 14+): deferral of 7 days for minor, 14 for major and 21 for system updates, Rapid Security Responses on including rollback. |",
        "| `MAC - D - Defender for Endpoint` | the organisation name of the content filter was set to *JAMF Software* — a leftover from the Jamf profiles the MDE documentation relies on. The user sees that name in System Settings → Network → Filters. |",
        "| `MAC - U - Compliance Device Health` and `Device Security` | carried each other's description. Device Health checks System Integrity Protection; Device Security checks encryption, the firewall and Gatekeeper. |",
        "",
        "One gap is deliberately left open: `MAC - U - Compliance Password` requires a password of",
        "at least eight characters with a lock after fifteen minutes, but there is no configuration policy",
        "that sets that on the Mac. A Mac without a screen lock is therefore reported as non-compliant",
        "but does not get the setting enforced — that needs its own passcode policy.",
        "",
        "## What still needs to happen",
        "",
        "The repo is ready and the checks are green. The tenant has not been touched: the policies",
        "there still carry their old name. The order is a dependency, not a suggestion —",
        "step 4 before step 3 produces two policies that contradict each other.",
        "",
        "| # | Step | |",
        "|---:|---|---|",
        "| 1 | Inventory | `Get-BaselinePolicyState.ps1` — still to be built |",
        "| 2 | Rename | `Rename-BaselinePolicy.ps1 -WhatIf` first; PATCH, so id and assignments stay |",
        "| 3 | Replace | Windows Firewall and Office Updates change policy type — manual work |",
        "| 4 | Retire | delete Network Security, Windows Search, System Services, OneDrive KFM |",
        "| 5 | Deploy | the new policies via CIPP or `Start-IntuneRestoreConfig` |",
        "| 6 | Assign | `Set-BaselineAssignment.ps1 -Scope D -AllDevices` and `-Scope U -AllUsers` only take phase 1; the pilot follows with `-GroupName 'SEC-Baseline-Pilot'` |",
        "| 7 | Inventory again | the list of orphaned policies must be empty |",
        "",
        "## Pilot first",
        "",
        "Phase 2 in `_manifest.json`. These policies are deployed via the package `CXNM - Standard - Baseline-Pilot` to",
        "`SEC-Baseline-Pilot`, and only to everyone once they move to phase 1 — a PR, because that",
        "changes who they are deployed to. The reason per policy is the `faseWaarom` from the manifest.",
        "",
        "| Policy | Why |",
      ],
      fr: [
        "## Ce qui a changé en août 2026",
        "",
        "De 24 policies maison à l'ensemble actuel.",
        "",
        "| | Nombre | |",
        "|---|---:|---|",
        "| Réécrites sur le contenu OIB | 15 | Edge Security est passé de 2 à 54 paramètres, Defender Antivirus de 11 à 28, Audit de 23 à 40 |",
        "| Nouvelles | 75 | notamment Windows Hello for Business, Credential Guard, Local Administrators, Office Security, 7 policies de conformité, 20 policies macOS, 2 BYOD MAM |",
        "| Fusionnées dans une autre policy | 6 | Administrative Templates (300 paramètres) éclaté ; Network Security, System Services, Windows Search et OneDrive KFM absorbés |",
        "| Reprises sans changement | 5 | là où OIB n'a pas d'équivalent : onboarding EDR, configuration automatique d'Outlook, moteur de recherche Edge, anneau de mise à jour 3, expérience utilisateur |",
        "",
        "Les paramètres que seule la baseline propre avait — le chiffrement des disques fixes et amovibles,",
        "par exemple — ont été conservés lors d'une réécriture au lieu de disparaître",
        "silencieusement.",
        "",
        "## Ce qu'a donné la comparaison avec IntuneAdmin",
        "",
        "Fin août 2026, l'ensemble a été comparé à [IntuneAdmin/IntuneBaselines](https://github.com/IntuneAdmin/IntuneBaselines)",
        "— 874 profils, comparés sur settingDefinitionId et valeur. 654 paramètres figurent dans",
        "les deux ensembles, dont 55 avec une valeur différente. Cela a donné quatre nouvelles policies et trois",
        "ajustements :",
        "",
        "| | |",
        "|---|---|",
        "| `WIN - D - Windows AI` | Recall et Click To Do désactivés. OIB v4.0 n'a pas encore de policy Windows AI, la baseline n'en avait donc pas non plus. |",
        "| `WIN - D - Removable Storage` | écriture sur stockage USB et appareils WPD bloquée ; les supports amovibles n'étaient restreints nulle part. |",
        "| `WIN - U - Windows Hello for Business` | WHfB par utilisateur, en plus de la policy par appareil existante. |",
        "| `WIN - D - Windows Hello for Business Multi User` | WHfB pour les appareils partagés, sans provisionnement juste après la connexion. |",
        "| `WIN - D - Windows Firewall` | *local policy merge* n'était défini que sur le profil public ; désormais aussi sur domaine et privé. |",
        "| `WIN - D - Login and Lock Screen` | le bouton d'affichage du mot de passe est désactivé — le seul écart CIS L1 strict sans raison fonctionnelle. |",
        "| `WIN - D - Defender Antivirus` | menaces faibles et moyennes en quarantaine au lieu de bloquer et supprimer : un faux positif peut alors être annulé. |",
        "",
        "En outre, les trois templates standard CIPP pour Defender ont perdu leur affectation. Ils définissaient",
        "les mêmes paramètres que leur équivalent OIB avec une autre valeur — 19 conflits au total,",
        "dont 16 règles ASR. En cas de conflit, Intune n'applique le paramètre d'aucune des deux policies,",
        "ces 16 règles étaient donc de fait désactivées.",
        "",
        "Ce qui reste volontairement différent de CIS et IntuneAdmin : télémétrie sur *Facultatif* (Endpoint Analytics",
        "et les rapports Windows Update en dépendent) et localisation activée (Localiser mon appareil, fuseau horaire). Les deux",
        "sont justifiés dans le champ `doel` de leur policy.",
        "",
        "## Ce qu'a donné la revue macOS",
        "",
        "Fin août 2026, l'ensemble macOS a été revu dans sa totalité. Cela a donné deux nouvelles policies",
        "et trois corrections :",
        "",
        "| | |",
        "|---|---|",
        "| `MAC - D - Enrollment Profile Administrator / Standard User Affinity` | deux profils d'inscription ADE qui diffèrent d'un seul paramètre : le compte connecté devient-il administrateur ou utilisateur standard. Alternatives l'un de l'autre, donc aucun n'est affecté. |",
        "| `MAC - D - Software Updates` | du payload classique `com.apple.softwareupdate` à la gestion déclarative des mises à jour (DDM, macOS 14+) : report de 7 jours pour les mises à jour mineures, 14 pour les majeures et 21 pour les mises à jour système, Rapid Security Responses activées avec retour arrière. |",
        "| `MAC - D - Defender for Endpoint` | le nom d'organisation du filtre de contenu était *JAMF Software* — un reste des profils Jamf sur lesquels s'appuie la documentation MDE. L'utilisateur voit ce nom dans Réglages Système → Réseau → Filtres. |",
        "| `MAC - U - Compliance Device Health` et `Device Security` | portaient la description l'une de l'autre. Device Health vérifie System Integrity Protection ; Device Security vérifie le chiffrement, le pare-feu et Gatekeeper. |",
        "",
        "Une lacune est volontairement laissée ouverte : `MAC - U - Compliance Password` exige un mot de passe",
        "d'au moins huit caractères avec verrouillage après quinze minutes, mais aucune policy de configuration",
        "ne le définit sur le Mac. Un Mac sans verrouillage d'écran est donc signalé comme non conforme",
        "sans que le paramètre lui soit imposé — cela nécessite une policy de code d'accès dédiée.",
        "",
        "## Ce qui reste à faire",
        "",
        "Le dépôt est prêt et les contrôles sont au vert. Le tenant n'a pas été touché : les policies",
        "y portent encore leur ancien nom. L'ordre est une dépendance, pas une suggestion —",
        "l'étape 4 avant l'étape 3 produit deux policies qui se contredisent.",
        "",
        "| # | Étape | |",
        "|---:|---|---|",
        "| 1 | Inventorier | `Get-BaselinePolicyState.ps1` — reste à construire |",
        "| 2 | Renommer | `Rename-BaselinePolicy.ps1 -WhatIf` d'abord ; PATCH, donc l'id et les affectations sont conservés |",
        "| 3 | Remplacer | Windows Firewall et Office Updates changent de type de policy — travail manuel |",
        "| 4 | Supprimer | supprimer Network Security, Windows Search, System Services, OneDrive KFM |",
        "| 5 | Déployer | les nouvelles policies via CIPP ou `Start-IntuneRestoreConfig` |",
        "| 6 | Affecter | `Set-BaselineAssignment.ps1 -Scope D -AllDevices` et `-Scope U -AllUsers` ne prennent que la phase 1 ; le pilote suit avec `-GroupName 'SEC-Baseline-Pilot'` |",
        "| 7 | Inventorier à nouveau | la liste des policies orphelines doit être vide |",
        "",
        "## D'abord en pilote",
        "",
        "Phase 2 dans `_manifest.json`. Ces policies sont déployées via le package `CXNM - Standard - Baseline-Pilot` vers",
        "`SEC-Baseline-Pilot`, et à tout le monde seulement lorsqu'elles passent en phase 1 — une PR, car cela",
        "change à qui elles sont déployées. La raison pour chaque policy est le `faseWaarom` du manifeste.",
        "",
        "| Policy | Pourquoi |",
      ],
    }),
    "|---|---|",
    ...pilot.map((p) => `| \`${p.displayName.replace(/^CXNM - Standard - /, "")}\` | ${escapePipes(V.d(p.faseWaarom))} |`),
    "",
    ...V.t({
      nl: [
        `Zonder toewijzing staan er ${unassigned.length}: de ${pilot.length} hierboven, ${byFase(3)} die op een voorwaarde`,
        `wachten, ${byFase(4)} voor een eigen groep en ${byFase(5)} die niet uitrollen. Die laatste twee zijn een`,
        "*alternatief* voor een policy die wél is toegewezen, niet een aanvulling erop: de update-ringen",
        "1 en 2 voor Windows en Defender zetten dezelfde instellingen als ring 3 met andere waarden, de",
        "drie CIPP-standaardtemplates voor Defender doen hetzelfde als hun OIB-tegenhanger, de",
        "WHfB-variant voor gedeelde apparaten hoort op een groep met gedeelde apparaten, en de twee",
        "macOS-inschrijfprofielen verschillen in precies één instelling. Allemaal op All Devices zou",
        "een conflict opleveren, waarna Intune de betwiste instelling door géén van beide policies",
        "toepast; die horen op een eigen groep.",
      ],
      en: [
        `${unassigned.length} are without assignment: the ${pilot.length} above, ${byFase(3)} awaiting a prerequisite,`,
        `${byFase(4)} for a dedicated group and ${byFase(5)} that are not deployed. The last two are an`,
        "*alternative* to a policy that is assigned, not an addition to it: update rings",
        "1 and 2 for Windows and Defender set the same settings as ring 3 with different values, the",
        "three CIPP standard templates for Defender do the same as their OIB counterpart, the",
        "WHfB variant for shared devices belongs on a group of shared devices, and the two",
        "macOS enrolment profiles differ in exactly one setting. All of them on All Devices would",
        "produce a conflict, after which Intune applies the disputed setting from neither",
        "policy; they belong on a dedicated group.",
      ],
      fr: [
        `${unassigned.length} sont sans affectation : les ${pilot.length} ci-dessus, ${byFase(3)} en attente d'un prérequis,`,
        `${byFase(4)} pour un groupe dédié et ${byFase(5)} qui ne sont pas déployées. Ces deux dernières catégories sont une`,
        "*alternative* à une policy affectée, pas un complément : les anneaux de mise à jour",
        "1 et 2 pour Windows et Defender définissent les mêmes paramètres que l'anneau 3 avec d'autres valeurs, les",
        "trois templates standard CIPP pour Defender font la même chose que leur équivalent OIB, la",
        "variante WHfB pour appareils partagés va sur un groupe d'appareils partagés, et les deux",
        "profils d'inscription macOS diffèrent d'un seul paramètre. Tout mettre sur All Devices",
        "provoquerait un conflit, après quoi Intune n'applique le paramètre contesté d'aucune des deux",
        "policies ; elles vont sur un groupe dédié.",
      ],
    }),
    "",
  ].join("\n");
}

function main() {
  const checkOnly = process.argv.includes("--check");
  const dumpMissing = process.argv.includes("--missend");
  const quiet = dumpMissing;
  const log = (...a) => (quiet ? null : console.log(...a));
  const templates = readTemplates(TEMPLATE_DIR);
  const assignments = fs.existsSync(ASSIGNMENTS_PATH) ? JSON.parse(fs.readFileSync(ASSIGNMENTS_PATH, "utf8")) : {};
  const manifest = fs.existsSync(MANIFEST_PATH) ? JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8")) : { policies: [] };
  const manifestByTarget = new Map(manifest.policies.map((p) => [p.target, p]));
  const vocab = fs.existsSync(CONTROLS_PATH) ? JSON.parse(fs.readFileSync(CONTROLS_PATH, "utf8")) : { iso27001: { controls: [] } };
  const isoById = new Map(vocab.iso27001.controls.map((c) => [c.id, c]));

  const ca = loadCaLinks();
  const known = new Set(templates.map((t) => t.baseName));
  for (const baseName of Object.keys(ca.snapshot.koppelingen || {})) {
    if (!known.has(baseName)) console.warn(`Let op: CA-koppeling naar ${baseName}, maar dat template bestaat hier niet — pas docs/policies.json in de CA-Policies-repo aan.`);
  }
  if (!ca.root && !quiet) log("CA-Policies-repo niet ernaast: de CA-koppelingen komen uit IntuneTemplate/_ca.json.");

  const ctx = { assignments, manifestByTarget, manifest, isoById, ca };
  const files = ca.content ? [{ file: CA_SNAPSHOT_PATH, content: ca.content }] : [];
  const translators = [];

  for (const lang of LANGS) {
    V = new Translator(lang);
    translators.push(V);
    const add = (file, content) => files.push({ file: variantPath(file, lang), content });

    add(path.join(REPO_ROOT, "docs", "OVERZICHT.md"), overviewDocument(templates, ctx));
    add(path.join(TEMPLATE_DIR, "README.md"), overviewReadme(templates, ctx));

    for (const platform of Object.keys(PLATFORMS)) {
      const list = templates.filter((t) => parseBaseName(t.baseName).platform === platform);
      if (list.length === 0) continue;
      add(path.join(TEMPLATE_DIR, platform, "README.md"), platformReadme(platform, list, ctx));
    }

    // Eén document per policy, naast de JSON.
    for (const template of templates) add(template.filePath.replace(/\.json$/, ".md"), policyDocument(template, ctx));
  }

  if (dumpMissing) {
    reportMissing(translators, process.argv, "generate-docs.js");
    return;
  }

  const stale = [];
  for (const { file, content } of files) {
    const rel = path.relative(REPO_ROOT, file).split(path.sep).join("/");
    const before = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
    if (before === content) {
      log(`  ongewijzigd  ${rel}`);
      continue;
    }
    stale.push(rel);
    if (checkOnly) {
      log(`  VEROUDERD    ${rel}`);
      continue;
    }
    fs.writeFileSync(file, content);
    log(`  ${before === null ? "nieuw       " : "bijgewerkt  "} ${rel}`);
  }

  reportMissing(translators, process.argv, "generate-docs.js");

  if (checkOnly && stale.length > 0) {
    console.error(`\n${stale.length} README('s) lopen achter. Draai: node scripts/generate-docs.js`);
    process.exit(1);
  }
  console.log(`\n${files.length} README('s) gecontroleerd, ${stale.length} ${checkOnly ? "verouderd" : "geschreven"}.`);
}

main();
